# Server configurations
server:
  url: "http://192.168.101.235:8080/svetets/orchestrator/speech/payment/offline"
  req: "POST"
  limiter: 500

# Data configurations
files:
  path: "result/"

logger:
  path: "log/result.log"  


